config/routes.rb
Rails.application.routes.draw do

  resources :exercicios
  get 'favorites/update'
	get 'favorites/index'

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
    resources :exercises

    

  root to: 'pages#home'
  devise_for :users


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/exercise.rb
class Exercise < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :exercises
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :favorites
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
protect_from_forgery with: :exception
 #before_action :authenticate_user!

    def favorite_text
        return @favorite_exists ? "UnFavorite" : "Favorite"
    end

    helper_method :favorite_text
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController


  def index
	@exercises = Exercise.all
  end

  def new
  end

  def create
    @exercise = Exercise.new(exercise_params)
 
    @exercise.save
    redirect_to @exercise
  end

  def show
    @exercise = Exercise.find(params[:id])
    #@favorite_exists = Favorite.where(exercise: @exercise, user: current_user) == [] ? false : true
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private
  def exercise_params
    params.require(:exercise).permit(:name, :url, :category)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def update
  	favorite = Favorite.where(exercise: Exercise.find(params[:exercise]), user: current_user)
  	if Favorite == []
  		Favorite.create(exercise: Exercise.find(params[:exercise]), user: current_user)
  		@favorite_exists = true
  	else
  		favorite.destroy_all
  		@favorite_exists = false
  	end
  	respond_to do |format|
  		format.html()
  		format.js()
  	end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
protect_from_forgery with: :exception
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exercises_helper.rb
module ExercisesHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exercises/create.html.erb
<h1>Exercises#create</h1>
<p>Find me in app/views/exercises/create.html.erb</p>

app/views/exercises/destroy.html.erb
<h1>Exercises#destroy</h1>
<p>Find me in app/views/exercises/destroy.html.erb</p>

app/views/exercises/edit.html.erb
<h1>Exercises#edit</h1>
<p>Find me in app/views/exercises/edit.html.erb</p>

app/views/exercises/index.html.erb
<div class="text-center">
      <br><br><br><br>
      <h1>Lista de todos os exercícios</h1>
      <br><br>
       <% @exercises.each do |exercise| %>
        <h5>Nome: <%= link_to exercise.name, exercise, :name => exercise.name %></h5>
        <h5>Categoria: <%= exercise.category %></h5>
        <br><br>
       <% end %>
</div>

app/views/exercises/new.html.erb
<div class="text-center">
	<br><br>
	<h2>Adicionar novo exercício</h2>
	<br>
<%= form_with scope: :exercise, local: true do |form| %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>
 
  <p>
    <%= form.label :url %><br>
    <%= form.text_field :url %>
  </p>
 
  <p>
    <%= form.label :category %><br>
    <%= form.text_field :category %>
  </p>

  <p>
    <%= form.submit %>
    <br><br>
  </p>
<% end %>
</div>

app/views/exercises/show.html.erb
<div class ="container">
  <br><br>
  <h1><%= @exercise.name %></h1>
  <p>
    <strong>Categoria:</strong>
    <%= @exercise.category %>
  </p>
  <% if user_signed_in? %>
    <%= link_to favorite_text, favorites_update_path(exercise: @exercise), 
      id:'favorite_link', remote: true%>
  <% end %>
  <p class="text-center">
  <br><br>
  <iframe width="850" height="504" src='https://www.youtube.com/embed/<%= @exercise.url %>?
    rel=0&autoplay=<%= params[:autoplay] || 0 %>' frameborder='0' allowfullscreen></iframe>
  </p>

app/views/exercises/update.html.erb
<h1>Exercises#update</h1>
<p>Find me in app/views/exercises/update.html.erb</p>

app/views/favorites/index.html.erb
<% current_user.favorites.each do |favorite| %>
<h1>Seus exercícios favoritos:</h1>
<%= link_to favorite.exercise.name, favorite.exercise %>

<% end %>

app/views/favorites/update.js.erb
$('#favorite_link').text("<%= favorite_text %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>UFit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script src="/assets/jquery.js" type="text/javascript"></script>
    <script src="/assets/jquery_ujs.js" type="text/javascript"></script>

    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.7.0/css/all.css" integrity="sha384-6jHF7Z3XI3fF4XZixAuSu0gGKrXwoX/w3uFPxC56OtjChio7wtTGJWRW53Nhx6Ev" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <%= stylesheet_link_tag "grayscale" %>
    <%= stylesheet_link_tag "grayscale.min" %>
    <%= stylesheet_link_tag "custom" %>

  </head>

  <body>

  <div class="container-fluid">
    <nav class="navbar navbar-expand-lg navbar-dark" id="mainNav">
    <div class="container">
      <a class="navbar-brand" href="/">uFit</a>
      <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          
          <li class="nav-item">
             <a class="nav-link" href="/exercises">Exercícios</a>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
            <a class="nav-link" href="#">Plano Pessoal</a>
          </li>
          <% end %>

          <li class="navbar-text float-right nav-link">
          <% if user_signed_in? %>
            <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
            <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
          <% else %>
            <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
            <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
          <% end %>
          </li>
          
        </ul>
      </div>
    </div>
    </nav>
 </div>
 
  <%= yield %>
 
  <footer class="bg-black small text-center text-white-50">
    <div class="container">
      Copyright &copy; uFit 2019
    </div>
  </footer>
  </body>
</html>

app/views/pages/home.html.erb
<div class = "img_header">
	<%= image_tag("/assets/header.jpg", :class => "img-fluid") %>
</div>


<section id="projects" class="projects-section bg-light">
    <div class="container">

      <!-- Featured Project Row -->
      <div class="row align-items-center no-gutters mb-4 mb-lg-5">
        <div class="col-xl-8 col-lg-7">
          <%= image_tag("/assets/woman.jpg", :class => "img-fluid mb-3 mb-lg-0") %>
        </div>
        <div class="col-xl-4 col-lg-5">
          <div class="featured-text text-center text-lg-left">
            <h4>A solução para uma vida saudavél</h4>
            <p class="text-black-50 mb-0">Com vários exercícios que você pode fazer em qualquer lugar, sem necessidade de nada além do peso do seu corpo, uFit é o lugar para encontrar ajuda para uma vida mais fit.</p>
          </div>
        </div>
      </div>

      <br><br>
      <div class="text-center">
      <h2>Categorias de Exercícios</h2>
      <br><br><br>
      </div>
      <!-- Project One Row -->
      <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
        <div class="col-lg-6">
          <%= image_tag("/assets/arm.jpg", :class => "img-fluid") %>
        </div>
        <div class="col-lg-6">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-left">
                <h4 class="text-white">Braço</h4>
                <p class="mb-0 text-white-50">Exemplos: Flexão de braços, triceps no banco, barra fixa, entre outros...</p>
                <hr class="d-none d-lg-block mb-0 ml-0">
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Project Two Row -->
      <div class="row justify-content-center no-gutters">
        <div class="col-lg-6">
          <%= image_tag("/assets/leg.jpg", :class => "img-fluid") %>
        </div>
        <div class="col-lg-6 order-lg-first">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-right">
                <h4 class="text-white">Pernas</h4>
                <p class="mb-0 text-white-50">Exemplos: Agachamento, afundo, entre outros... </p>
                <hr class="d-none d-lg-block mb-0 mr-0">
              </div>
            </div>
          </div>
        </div>
      </div>

<!-- Project One Row -->
      <div class="row justify-content-center no-gutters mb-5 mb-lg-0">
        <div class="col-lg-6">
          <%= image_tag("/assets/abdomen.jpg", :class => "img-fluid") %>
        </div>
        <div class="col-lg-6">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-left">
                <h4 class="text-white">Abdômen</h4>
                <p class="mb-0 text-white-50">Exemplos: Abdominal, abdominal lateral, abdominal com elevação de quadril, entre outros...</p>
                <hr class="d-none d-lg-block mb-0 ml-0">
              </div>
            </div>
          </div>
        </div>
      </div>

      <!-- Project Two Row -->
      <div class="row justify-content-center no-gutters">
        <div class="col-lg-6">
          <%= image_tag("/assets/body.jpg", :class => "img-fluid") %>
        </div>
        <div class="col-lg-6 order-lg-first">
          <div class="bg-black text-center h-100 project">
            <div class="d-flex h-100">
              <div class="project-text w-100 my-auto text-center text-lg-right">
                <h4 class="text-white">Exercícios aeróbicos</h4>
                <p class="mb-0 text-white-50">Exemplos: Corrida, exercício com corda, polichinelo, entre outros...</p>
                <hr class="d-none d-lg-block mb-0 mr-0">
              </div>
            </div>
          </div>
        </div>
      </div>



    </div>
  </section>